name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  syntax-check:
    runs-on: Agent-1
    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Frontend syntax check
      - name: Frontend Compilation (JS Syntax Check)
        run: |
          cd frontend
          find . -name "*.js" -exec node --check {} +

      # Backend syntax check
      - name: Backend Compilation (JS Syntax Check)
        run: |
          cd backend
          find . -name "*.js" -exec node --check {} +

  gitleaks-scan:
    runs-on: Agent-1
    needs: syntax-check   # ensures it runs after syntax-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --redact --exit-code 1 --report-path=gitleaks-report.json

  trivy-scan:
    runs-on: Agent-1
    needs: gitleaks-scan   # ensures it runs after gitleaks-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: .
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
