name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  syntax-check:
    runs-on: Agent-1
    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Frontend syntax check
      - name: Frontend Compilation (JS Syntax Check)
        run: |
          cd frontend
          find . -name "*.js" -exec node --check {} +

      # Backend syntax check
      - name: Backend Compilation (JS Syntax Check)
        run: |
          cd backend
          find . -name "*.js" -exec node --check {} +

  gitleaks-scan:
    runs-on: Agent-1
    needs: syntax-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --redact --exit-code 1 --report-path=gitleaks-report.json

  trivy-scan:
    runs-on: Agent-1
    needs: gitleaks-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: .
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  sonar-frontend:
    runs-on: Agent-1
    needs: trivy-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan (Frontend)
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.projectKey=myorg_frontend
            -Dsonar.projectName=myorg_frontend
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  sonar-backend:
    runs-on: Agent-1
    needs: sonar-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan (Backend)
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.projectKey=myorg_backend
            -Dsonar.projectName=myorg_backend
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
